### ISSUE TITLE
sac_learn --train was crash

### ISSUE THREAD

**Issue by leeivan1007** [deep-reinforcement-learning-book/Project2-RL-for-Robotics#1]
Package version：
V-REP 3.6.2
torch 1.4.0
It will be crash when I run the train mode.

![image](https://user-images.githubusercontent.com/14324351/78983529-f7062380-7b56-11ea-8e80-c44e19829001.png)

**Comment by leeivan1007** [comment]
I had changed the version of torch. 1.4->1.2 
but it is the same outcome.
Version:
torch:1.2.0
gym:0.15.4
v-rep:3.6.2

this is the other infomation that I stop the progress:
![2020-04-15 12-16-12 的螢幕擷圖](https://user-images.githubusercontent.com/14324351/79302817-f9ce9300-7f1f-11ea-865b-2632667d510c.png)

**Comment by quantumiracle** [comment]
Hi, 
Could you please provide more information or log details when the program crashed? It seems several processes have been called, so is it caused by overuse of memory or GPUs?
Zihan

**Comment by leeivan1007** [comment]
I find the problem that the GPU memory is no enough. when I close the web browser, the problem is saved. Think you!
